name: "Ext"

exports: "mootools-ext.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools, The JavaScript framework"

license: Public domain, http://unlicense.org

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "Random folks"

sources:
  - "Source/Types/Event.js"
  - "Source/Types/String.js"
  - "Source/Types/Object.js"
  - "Source/Types/FastArray.js"
  - "Source/Element/Element.js"
  - "Source/Element/Events/Keypress.js"
  - "Source/Element/Events/Input.js"
  - "Source/Element/Properties/Data.js"
  - "Source/Element/Properties/Widget.js"
  - "Source/Element/Element.Selection.js"
  - "Source/Element/Element.from.js"
  - "Source/Element/Element.onDispose.js"
  - "Source/Element/Properties/Item.js"
  - "Source/Element/Properties/Data.js"
  - "Source/Element/Properties/Widget.js"
  - "Source/Element/Properties/BoxShadow.js"
  - "Source/Element/Properties/BorderRadius.js"
  - "Source/Element/Properties/UserSelect.js"
  - "Source/Utilities/Observer.js"
  - "Source/Core/Class.Includes.js"
  - "Source/Core/Class.States.js"
  - "Source/Core/Class.Shortcuts.js"
  - "Source/Core/Class.Macros.js"
  - "Source/Core/Class.Mixin.js"
  - "Source/Core/Class.Binds.Remover.js"
  - "Source/Drag/Drag.Limits.js"
  - "Source/Drag/Slider.js"
  - "Source/Request/Request.Form.js"
  - "Source/Request/Request.Headers.js"
  - "Source/Request/Request.Statuses.js"
  - "Source/Request/Request.Auto.js"