name: "Ext"

exports: "mootools-ext.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools, The JavaScript framework"

license: Public domain, http://unlicense.org

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "Random folks"

sources:
  - "Source/Types/Event.js"
  - "Source/Types/FastArray.js"
  - "Source/Element/Events/Keypress.js"
  - "Source/Element/Properties/Data.js"
  - "Source/Element/Properties/Widget.js"
  - "Source/Element/Element.Selection.js"
  - "Source/Element/Properties/Item.js"
  - "Source/Element/Properties/Data.js"
  - "Source/Element/Properties/Widget.js"
  - "Source/Element/Properties/BoxShadow.js"
  - "Source/Element/Properties/BorderRadius.js"
  - "Source/Element/Properties/UserSelect.js"
  - "Source/Utilities/Observer.js"
  - "Source/Utilities/Logger.js"
  - "Source/Core/Class.Includes.js"
  - "Source/Core/Class.States.js"
  - "Source/Core/Class.Macros.js"
  - "Source/Core/Class.Binds.Remover.js"
  - "Source/Core/Class.Speedups.js"
  - "Source/Core/Class.Extras.Speedups.js"
  - "Source/Core/Core.Speedups.js"
  - "Source/Drag/Drag.Limits.js"
  - "Source/Drag/Slider.js"